import type { ViewProjection } from '@icarus-graph-explorer/view-projection';

export function localTestProjection(): ViewProjection {
  return {
    nodes: [
      {
        id: 'entity:root',
        kind: 'entity',
        entityId: 'root',
        entityKind: 'document',
        sourcePath: 'Root.md',
        sourceStartLine: 1,
        title: null,
        revealableDescendantCount: 1,
        internalReferenceIds: [],
        role: 'content',
        focusDistance: 0,
      },
      {
        id: 'entity:heading',
        kind: 'entity',
        entityId: 'heading',
        entityKind: 'section',
        sourcePath: 'Root.md',
        sourceStartLine: 2,
        title: 'Heading',
        revealableDescendantCount: 1,
        internalReferenceIds: [],
        role: 'content',
        focusDistance: 0,
      },
      {
        id: 'entity:block',
        kind: 'entity',
        entityId: 'block',
        entityKind: 'block',
        sourcePath: 'Root.md',
        sourceStartLine: 3,
        title: null,
        revealableDescendantCount: 0,
        internalReferenceIds: [],
        role: 'content',
        focusDistance: 0,
      },
      {
        id: 'entity:neighbor',
        kind: 'entity',
        entityId: 'neighbor',
        entityKind: 'document',
        sourcePath: 'folder/Neighbor.md',
        sourceStartLine: 1,
        title: null,
        revealableDescendantCount: 2,
        internalReferenceIds: [],
        role: 'content',
        focusDistance: 1,
      },
      {
        id: 'diagnostic:missing',
        kind: 'reference-target',
        status: 'unresolved',
        rawTarget: 'Missing',
        referenceIds: ['r-missing'],
        candidateEntityIds: [],
        reasons: ['No match.'],
      },
    ],
    edges: [
      {
        id: 'hierarchy:root-heading',
        kind: 'hierarchy',
        sourceNodeId: 'entity:root',
        targetNodeId: 'entity:heading',
      },
      {
        id: 'hierarchy:heading-block',
        kind: 'hierarchy',
        sourceNodeId: 'entity:heading',
        targetNodeId: 'entity:block',
      },
      {
        id: 'reference:neighbor',
        kind: 'reference',
        sourceNodeId: 'entity:heading',
        targetNodeId: 'entity:neighbor',
        status: 'resolved',
        referenceIds: ['r-neighbor'],
      },
      {
        id: 'reference:missing',
        kind: 'reference',
        sourceNodeId: 'entity:heading',
        targetNodeId: 'diagnostic:missing',
        status: 'unresolved',
        referenceIds: ['r-missing'],
      },
    ],
    issues: [],
  };
}
